### ISSUE TITLE
Vertical position seems to be incorrect for a file

### ISSUE THREAD

**Issue by Iey4iej3** [Krasjet/pdf.tocgen#30]
Sample PDF: https://www.math.ias.edu/~lurie/papers/HTT.pdf

If I run `pdftocgen -v` with the TOML file

``` TOML
level = 1
greedy = true
font.name = "CMBX10"
font.size = 9.962599754333496
```

I get a TOC with a line
```
"1.1 FOUNDATIONS FOR HIGHER CATEGORY THEORY" 19 484.73089599609375
```

and if I use `pdftocio` to write the TOC into the PDF, and open the result PDF by PDF viewers (I tested `zathura` and `okular`), the vertical position seems to be incorrect.

pdf.tocgen v1.3.3
Python 3.11.2
